version: '3'

services:
    mysql:
        image: mysql:latest
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: octohaus
            MYSQL_DATABASE: octohaus
            MYSQL_USER: octohaus
            MYSQL_PASSWORD: octohaus

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        links:
            - mysql
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
        ports:
            - "8080:80"




